/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import javax.swing.JOptionPane;

import com.formdev.flatlaf.FlatLightLaf;

/**
 *
 * @author Nicholas.Sixbury
 */
public class ThresholdDialog extends javax.swing.JDialog {
    
    public int thresholdToReturn = 160;

    /**
     * Creates new form ThresholdDialog
     */
    public ThresholdDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        FlatLightLaf.setup();
        initComponents();
    }//end constructor

    /**
     * Updates the interface based on thresholdToReturn value.
     */
    public void updateInterface() {
//        if (thresholdToReturn == 160) {
//            uxTh160Btn.setSelected(true);
//            uxTh180Btn.setSelected(false);
//            uxThOtherBtn.setSelected(false);
//            uxOtherThSpnr.setValue(thresholdToReturn);
//        }
//        else if (thresholdToReturn == 180) {
//            uxTh160Btn.setSelected(false);
//            uxTh180Btn.setSelected(true);
//            uxThOtherBtn.setSelected(false);
//            uxOtherThSpnr.setValue(thresholdToReturn);
//        }
//        else {
//            uxTh160Btn.setSelected(false);
//            uxTh180Btn.setSelected(false);
//            uxThOtherBtn.setSelected(true);
//            uxOtherThSpnr.setValue(thresholdToReturn);
//        } TODO: Handle this
    }//end updateInterface()

    @Override
    public void setVisible(boolean visibility) {
        updateInterface();
        super.setVisible(visibility);
    }//end setVisible

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uxSetThBtnGrp = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        uxConfirmBtn = new javax.swing.JButton();
        uxCancelBtn = new javax.swing.JButton();
        uxKernelThSpnr = new javax.swing.JSpinner();
        uxChalkThSpnr = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        uxResetChkThBtn = new javax.swing.JButton();
        uxResetKernThBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thresholds");
        setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getSize()+2f));
        jLabel1.setText("Set Thresholds For Image Processing");

        uxConfirmBtn.setFont(uxConfirmBtn.getFont().deriveFont(uxConfirmBtn.getFont().getSize()+2f));
        uxConfirmBtn.setText("Confirm");
        uxConfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uxConfirmBtnActionPerformed(evt);
            }
        });

        uxCancelBtn.setFont(uxCancelBtn.getFont().deriveFont(uxCancelBtn.getFont().getSize()+2f));
        uxCancelBtn.setText("Cancel");
        uxCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uxCancelBtnActionPerformed(evt);
            }
        });

        uxKernelThSpnr.setFont(uxKernelThSpnr.getFont().deriveFont(uxKernelThSpnr.getFont().getSize()+2f));
        uxKernelThSpnr.setModel(new javax.swing.SpinnerNumberModel(60, 0, 255, 1));

        uxChalkThSpnr.setFont(uxChalkThSpnr.getFont().deriveFont(uxChalkThSpnr.getFont().getSize()+2f));
        uxChalkThSpnr.setModel(new javax.swing.SpinnerNumberModel(185, 0, 255, 1));

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getSize()+2f));
        jLabel2.setText("Kernel Threshold");

        jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getSize()+2f));
        jLabel3.setText("Chalk Threshold");

        uxResetChkThBtn.setFont(uxResetChkThBtn.getFont().deriveFont(uxResetChkThBtn.getFont().getSize()+2f));
        uxResetChkThBtn.setText("<");
        uxResetChkThBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uxResetChkThBtnActionPerformed(evt);
            }
        });

        uxResetKernThBtn.setFont(uxResetKernThBtn.getFont().deriveFont(uxResetKernThBtn.getFont().getSize()+2f));
        uxResetKernThBtn.setText("<");
        uxResetKernThBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uxResetKernThBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(uxCancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uxConfirmBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(uxKernelThSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(uxResetKernThBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(uxChalkThSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(uxResetChkThBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uxKernelThSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(uxResetKernThBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uxChalkThSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(uxResetChkThBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uxCancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(uxConfirmBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uxConfirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uxConfirmBtnActionPerformed
        // TODO: handle this
        this.setVisible(false);
    }//GEN-LAST:event_uxConfirmBtnActionPerformed

    private void uxCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uxCancelBtnActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_uxCancelBtnActionPerformed

    private void uxResetKernThBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uxResetKernThBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uxResetKernThBtnActionPerformed

    private void uxResetChkThBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uxResetChkThBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uxResetChkThBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton uxCancelBtn;
    private javax.swing.JSpinner uxChalkThSpnr;
    private javax.swing.JButton uxConfirmBtn;
    private javax.swing.JSpinner uxKernelThSpnr;
    private javax.swing.JButton uxResetChkThBtn;
    private javax.swing.JButton uxResetKernThBtn;
    private javax.swing.ButtonGroup uxSetThBtnGrp;
    // End of variables declaration//GEN-END:variables
}
